version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /mnt/storage/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=8DBaE6fx
      - MYSQL_PASSWORD=rKUFeXf8
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - /mnt/storage/nextcloud/main:/var/www/html
      - /mnt/storage/nextcloud/apps:/var/www/html/custom_apps
      - /mnt/storage/nextcloud/config:/var/www/html/config
      - /mnt/storage/nextcloud/data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=rKUFeXf8
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
