version: "3"

services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/storage/docker_volumes/nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      - NGINX_HOST=lastoption.mooo.com
      - NGINX_PORT=80
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

