version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
        # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /mnt/storage/docker_volumes/jellyfin/config:/config
      - /mnt/storage/docker_volumes/jellyfin/data/tvshows:/data/tvshows
      - /mnt/storage/docker_volumes/jellyfin/data/movies:/data/movies
      - /mnt/storage/docker_volumes/jellyfin/data/anime:/data/anime
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
