version: "3"
services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    name: valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - /mnt/storage/docker_volumes/valheim-server/config:/config
      - /mnt/storage/docker_volumes/valheim-server/data:/opt/valheim
    ports: 
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    environment:
      - SERVER_NAME=Poundtown
      - WORLD_NAME=Poundtown
      - SERVER_PASS=PILAS
      - SERVER_PUBLIC=true
    restart: unless-stopped
    stop_grace_period: 2m
